version: '3.3'

volumes:
  postgres:
  pgadmin:

services:
  postgres:
    container_name: authenticator_db
    labels:
      # see https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.docker-compose.custom-images for details
      org.springframework.boot.service-connection: postgres
    image: "postgres:15"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "vampyrrr9712"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker_postgres_multidb_init.sh:/docker-entrypoint-initdb.d/multidb_init.sh
    ports:
      - "15433:5432"
    restart: unless-stopped
  
  pgadmin:
    container_name: authenticator_pgadmin
    labels:
      org.springframework.boot.ignore: true
    image: "dpage/pgadmin4:7.4"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - "181:80"
    entrypoint:
      - "/bin/sh"
      - "-c"  
      - "/bin/echo 'postgres:5432:*:postgres:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    restart: unless-stopped