server:
  port: 8081
  servlet:
    context-path: /book-shop-authenticator
spring:
  datasource:
    url: jdbc:postgresql://localhost/Authenticator
    driverClassName: org.postgresql.Driver
    username: postgres
    password: vampyrrr9712

session:
  expiration:
    minutes: 20